name: Build Docker image for tag.

on:
 push:
    tags:
      - '*'

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image
      run: |
        docker build -f environment/Dockerfile -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

    - name: Authenticate to the container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
